apiVersion: apps/v1
kind: Deployment
metadata:
     name: 1test1111
     labels:
        app: appsa-vi01
spec:
  replicas: 4
  selector:
      matchLabels:
          app: appsa-vi01
  template:
      metadata:
          labels:
               app: appsa-vi01
      spec:
        containers:
        - name: 1test1111
          image: saikumarpanda28/javaproject:latest
          ports:
          - containerPort: 8080
                    
---                    
                    
apiVersion: v1
kind: Service
metadata:
  name: maven-apptest
  namespace: default
spec:
  selector:
    app: appsa-vi01
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 32004
