apiVersion: apps/v1
kind: Deployment
metadata:
  name: 0809test
  labels:
    app: app-0809test
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: app-0809test
  template:
    metadata:
      labels:
        app: app-0809test
    spec:
      containers:
      - name: cont-0809test
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: 0809testvolume
          mountPath: /usr/local/tomcat/webapps
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
      volumes:
      - name: 0809testvolume
        hostPath:
          path: /mytest/
      imagePullSecrets:
      - name: saitest2
      nodeSelector:
        name: node1

---
apiVersion: v1
kind: Service
metadata:
  name: svc0809
  labels:
    app: app-0809test
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 32040
    targetPort: 80
  selector:
    app: app-0809test
  type: NodePort
