apiVersion: apps/v1
kind: Deployment
metadata:
  name: somtest
  labels:
    app: app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
      - name: saomtest
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mountpathandhost
          mountPath: /usr/nginx
      volumes:
      - name: mountpathandhost
        hostPath:
          path: /opt
      imagePullSecrets:
      - name: saisai
      nodeSelector:
        name: node1

---                    
                    
apiVersion: v1
kind: Service
metadata:
  name: maven-apptest
  namespace: default
spec:
  selector:
    app: appsa-vi01
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 32004
