apiVersion: apps/v1
kind: Deployment
metadata:
  name: somename
  labels:
    app: myapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapispec
        ports:
        - containerPort: 80
        image: nginx:latest
        resources:
          requests:
            cpu: "2m"
            memory: "2Mi"
          limits:
            cpu: "4m"
            memory: "4Mi"
        volumeMounts:
        - name: mountandhost
          mountPath: /usr/local
      volumes:
      - name: mountandhost
        hostPath:
          path: /mytest/
      imagePullSecrets:
      - name: saisaisai
      nodeSelector:
        name: node1

---                    
                    
apiVersion: v1
kind: Service
metadata:
  name: maven-apptest
  namespace: default
spec:
  selector:
    app: appsa-vi01
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 32004
